# server.port
server: 
  port: 8098

# spring.datasource.driverClassName
# spring.datasource.url
spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgres-container:5432/bc2412"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update


spring:
  data:
    redis:
      host: redis-container
      port: 6379
#spring.database:
#   platfrom:h2
#   url:jdbc:h2:man:jpademo

# # JPA Settings
# spring.jpa:
#   show-sql:true
#   hibernate.ddl-auto: create-drop #for development purpose

# # H2 Database Setting
# spring.h2.console.enbled: true

#Custom Variables
api:
  jsonplaceholder:
    domain: "jsonplaceholder.typicode.com"
    endpoints:
      users: "/users"
