FROM openjdk:17
LABEL maintainer="123@gmail.com"
ADD target/demo-customer-0.0.1-SNAPSHOT.jar demo-customer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "demo-customer-0.0.1-SNAPSHOT.jar"]
EXPOSE 8098