server:
  port: 8088
#spring.datasource.url=jdbc:postgresql://localhost:5432/simpleecommerceapp
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/simpleecommerceapp"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true