package com.demospcotroller;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import com.demospcotroller.entity.PersonEntity;
import com.demospcotroller.repository.PersonRepository;

@DataJpaTest //! load repository related beans only
// No Controller , No Service 
public class PersonRepositoryTest {
  @Autowired
  private PersonRepository personRepository;

  //! This Unit Test provded the repostiory bean, 
  //! generated by Hibernate, is correct.
  @Test 
  void testSaveAndFindAll() {
    //1. 
    List<PersonEntity> beforeSave = personRepository.findAll();
    //! assertEquals ---> 左邊expect，右邊 actural 
    assertEquals(0, beforeSave.size());

    //2.
    PersonEntity john = PersonEntity.builder()
        .email("john@gmail.com").name("john").id(1L).build(); //
        PersonEntity personEntity = personRepository.save(john);
        //! assertEquals ---> 左邊expect，右邊 actural 
    assertEquals("john", personEntity.getName());
    assertEquals("john@gmail.com", personEntity.getEmail());
    assertEquals(1L, personEntity.getId());

// 3.
List<PersonEntity> afterSaveJohn = personRepository.findAll();
//! assertEquals ---> 左邊expect，右邊 actural 
assertEquals(1, afterSaveJohn.size());

// 4.
    PersonEntity mary = PersonEntity.builder()
        .email("mary@gmail.com").name("mary").id(2L).build();
        PersonEntity personEntity2 = personRepository.save(mary);
        //! assertEquals ---> 左邊expect，右邊 actural 
        assertEquals("mary", personEntity2.getName());
        assertEquals("mary@gmail.com", personEntity2.getEmail());
        assertEquals(2L, personEntity2.getId());
  
//5.
List<PersonEntity> afterSaveMary = personRepository.findAll();
assertEquals(2, afterSaveMary.size());
      
}
  //左邊expect，右邊 actural
}
