server:
  port : 8088

api:
  coingecko:
    coin-market:
      url:
        base: "https://api.coingecko.com"
        version: "api/v3"
        coinsMarketsEndpoint: "/coins/markets"
        coinsOHLCEndpoint: "/coins/bitcoin/ohlc"
      param:
        vsCurrency: "usd"
        order: "market_cap_desc"
        ids: 
        per-page: 100
        page: 1
        sparkline: false
        price-change-percentage: "1h"
        days: 1 #OHLC
        x-cg-pro-api-key: "no6HUUo5LThHZgSz6ynmuGGD" 
      return:
        no-of-items: 20
#https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false&price_change_percentage=1h 

#https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=1&x-cg-pro-api-key=no6HUUo5LThHZgSz6ynmuGGD